### ISSUE TITLE
Changing this value crashes MadEdit.

### ISSUE THREAD

**Issue by Achaean** [LiMinggang/madedit-mod#263] opened 2018-04-20 19:00 UTC
**Please provide the following information**

Madedit-Mod version (or branch):
0.4.12
platform/architecture:
Win 10 x64 v.10.0.16299.371
compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and how to reproduce it.

Changing repeatedly the value from "Plain Text", to something other, crashing MadEdit.

![screenshot_1](https://user-images.githubusercontent.com/3608053/39068743-044925aa-44e6-11e8-816d-c9181ca777d5.png)

**Comment by LiMinggang** [comment] 2018-04-22 00:39
Do you have the crash dump file that would be generated under your madedit-mod directory?
Just tried several times and nothing happened.

**Comment by Achaean** [comment] 2018-04-23 15:15
1) Ehm...which one is the crash dump file? :-)
I can't locate it.

2) For reproducing it just select this option and start pressing the down arrow (so the next item should be activated).

**Comment by Achaean** [comment] 2018-04-23 15:18
**UPDATED info:**

After practicing a bit with it, seems like it doesn't actually crash (my bad).
It just stucks for anusuall long time.
Despite the Windows information that Madedit not responding, if you give it enough time (lets say 5min or more) it continues to work properly.

**Comment by LiMinggang** [comment] 2018-04-24 03:40
The crash file would be generated aromatically under your madedit-mod directory.
The file name would be something like Madedit_20180423T172442_67904.dmp.

Can your provide the steps if you can reproduce it constantly? 
I did met the issue while painting the html file and I added a patch for it since 0.4.12 I think, so it would work again after several seconds or minutes. I could not reproduce it easily although I met it lots of time with a large file.

**Comment by LiMinggang** [comment] 2018-05-23 06:11
Close it with 0.4.13. Please reopen it if you still see issues with 0.4.13

**Closed by LiMinggang** 2018-05-23 06:11 UTC

**Comment by Achaean** [comment] 2018-05-23 06:45
Probably a silly question, but...ehm...where are the binaries? :-)
Compiling at Windows is really complicated.

**Comment by LiMinggang** [comment] 2018-05-23 07:45
I did not upload yet because I'm in office now. Will upload from home this evening. Around 5 PM GMT+8 this evening.

**Comment by LiMinggang** [comment] 2018-05-23 07:47
I did a change to address the hang (for a long time )issue. I did not see side effect yet so I think it's a fix.
