### ISSUE TITLE
MadEdit not responding when open .java file

### ISSUE THREAD

**Issue by ooab** [LiMinggang/madedit-mod#267] opened 2018-05-07 03:10 UTC
**Please provide the following information**

Madedit-Mod version (or branch): 0.4.12

platform/architecture: windows7

compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and how to reproduce it.

Open a java source file(from main menu, drag&drop or explorer context menu), 
madedit ui hangs and not responsing 
after about 15 seconds, app recovers.

**Comment by LiMinggang** [comment] 2018-05-07 05:36
Yes. It has a bug but is hard to reproduce and fix. I made a patch in 0.4.12 that's why it can recover.
18.Fix: Patch for dead/infinite loop in syntax highlighting

The tricky stuff is that the issue would be gone when you load the same file for a second time.

It's a bug of syntax highlighting module.
https://github.com/LiMinggang/madedit-mod/commit/4e8d92b79cd8b2b764d875a274abdab09f95573e

I'm not sure when I can fix the issue instead of the patch.

**Comment by LiMinggang** [comment] 2018-05-12 01:02
Looks the patch worked. Did you want a try?

**Comment by LiMinggang** [comment] 2018-05-23 06:10
Close it with 0.4.13

**Closed by LiMinggang** 2018-05-23 06:10 UTC
Labels: bug

**Comment by ooab** [comment] 2018-07-09 08:42
the patch is not valid, the bug can be reproduced with version 0.4.13

**Comment by LiMinggang** [comment] 2018-07-09 09:00
Is it possible to share the java file you used to reproduce the issue? I used to met the issue by opening HTML file and don not see it for a long time.

**Comment by ooab** [comment] 2018-07-10 03:50
any .java file can reproduce it.  

```
package demos.str;
public class Hello {
    public static void main( String[] args ) {
        // TODO Auto-generated method stub
    }
}
```

After debugging, i think the problem should be syntax loading:

```
void MadSyntax::ParseSyntax( const wxString &filename )
{
     
    if( entry == wxT( "keyword" ) )
    {
        wxStringTokenizer tkz( value );
        wxString kw = tkz.GetNextToken();
        wxLongLong t1 = wxGetLocalTimeMillis();
        while( !kw.IsEmpty() )
        {
            if( ( kwlen = kw.size() ) > nw_MaxKeywordLen )
            {
                nw_MaxKeywordLen = kwlen;
            }

            if( !ck->m_CaseSensitive )
                kw.MakeLower();

            ck->m_Keywords.insert( kw );
            m_SyntaxKeywordDict->AddWord(kw);  /* inefficient */
            kw = tkz.GetNextToken();
        }
        wxLongLong t2 = wxGetLocalTimeMillis();
	wxString ms = wxString::Format(wxT("WHILE %dms\r\n"), (t2 - t1).ToLong()); 
        ::OutputDebugString(ms.t_str());
    }
    
}

void PersonalDictionary::AddWord(const wxString& strWord)
{
    wxString word = strWord.Lower();
    if(word.IsEmpty()) return;   
    m_DictionaryWords.Add(strWord.Lower());
    m_DictionaryWords.Sort(); /* inefficient */
}
```

when loading a syntax file, the code sort the whole dictionary after adding each keyword.
the problem is, in java syntax file, there are thousands of keywords,
the dictionary is sorted again and again, at same time,  size of dictionary increased, Sort()  getting slower and slower.

more efficient way could be:

```
void PersonalDictionary::AddWord(const wxString& strWord)
{
    wxString word = strWord.Lower();
    if(word.IsEmpty()) return;   
    m_DictionaryWords.Add(strWord.Lower());
    if( m_AutoSortEnabled ) 
    {
        m_DictionaryWords.Sort(); 
    }
}

m_SyntaxKeywordDict->DisableAutoSort();
while( .. ) 
{
    m_SyntaxKeywordDict->AddWord(kw)
}
m_SyntaxKeywordDict->EnableAutoSort();
m_SyntaxKeywordDict->Sort();
```

**Comment by LiMinggang** [comment] 2018-07-10 06:18
Good catch! Will refactor the code for syntax highlighting.

**Comment by LiMinggang** [comment] 2018-07-10 06:42
I used the code you suggested. Do you want my build or waiting for next release? I'm waiting for wxWigets 3.1.2 to release 0.4.14 which is mainly to fix the High DPI text blurry issue  of Windows 10.

**Comment by ooab** [comment] 2018-07-10 08:38
I will wait for your new release.
Currently, spellcheck is useless for me, so I just remove the line 'm_SyntaxKeywordDict->AddWord(kw)' and my build works fine for me.

**Comment by LiMinggang** [comment] 2018-07-10 11:48
Verified the issue and verified the fix. There was misunderstanding in the communication. I thought the issue you reported is the one I fixed but it is not.

Thanks for reporting the issue and the patch.

**Comment by LiMinggang** [comment] 2018-07-10 11:58
Syntax highlight for Java is still a little bit slower than others because of too many keywords. Will try to optimize it to reduce the time you opened two more java files.
