### ISSUE TITLE
hunspell personal dictionary, wrong path

### ISSUE THREAD

**Issue by nikoss** [LiMinggang/madedit-mod#238] opened 2017-08-29 21:17 UTC
Hi,
When I go to Madedit-mod's...
   
> Options --> Spellchecking 

and try to check the option...
  
>  |x| Enable Personal Dictionary

I get the message of the attached picture (error 13: access denial):

![hunspell_personal](https://user-images.githubusercontent.com/4921343/29844421-e062b0f6-8d17-11e7-8508-05c997b65bcd.png)

Obviously this is the wrong path.

My system is Linux, Mageia 6, x64, with Greek (el) language as the default, and I use...

> MadEdit-Mod 0.4.8 x86_x64 GCC 4.9.2 build 14:15:02 Jan 19 2017

Maybe the problem isn't there in the latest Madedit-mod versions.

**Comment by LiMinggang** [comment] 2017-08-30 11:47
Should be a bug which is also in the latest build. Will check code for the root cause.

**Comment by LiMinggang** [comment] 2017-08-30 11:50
BTW, Do you use Git on Mageia 6 X64? I can't even install git. It said: can't install because it is conflicted with perl-Git-2.xx.x. Any idea?

**Comment by LiMinggang** [comment] 2017-08-30 12:14
Will close it after I verified it on Mageia.

**Comment by nikoss** [comment] 2017-08-30 23:27
> BTW, Do you use Git on Mageia 6 X64? I can't even install git.

I just tried installing it, and there was no problem. Maybe it is an update thing. My version is git-2.13.5-1 .

**Comment by LiMinggang** [comment] 2017-08-31 04:26
I've fixed the problem by installing the git with higher version number.

**Comment by LiMinggang** [comment] 2017-09-01 02:03
I can't build RPM successfully with Mageia 6 yet. Is a preview binary OK for  you? I'll share it in the preview directory on sourceforge

**Comment by LiMinggang** [comment] 2017-09-01 03:48
Fixed

**Closed** 2017-09-01 06:32 UTC
Labels: bug

**Comment by LiMinggang** [comment] 2017-09-01 10:28
0.4.9 released
