### ISSUE TITLE
Double Window Border

### ISSUE THREAD

**Issue by bobsobol** [LiMinggang/madedit-mod#241] opened 2017-10-02 11:18 UTC
Simple to illustrate but hard to describe, I hope this is visible:-
[Animated Gif](https://s1.postimg.org/15y46qpovj/Mad_Edit_Mod.gif)
or if not [mp4](https://drive.google.com/file/d/0B0xbMmU1OqFCVk5nVDZiSUNfMmc/view)

So, (for the words) I'm illustrating the difference between wxMEdit (another continuation / bug-fix of MadEdit which I use) and MadEdit-Mod. (which looks better, aside from this bug, which makes it pretty unusable) MadEdit, works the same as wxMEdit. Something MadEdit-Mod has added, has also added an additional window, outside the main one, with no content at all. This makes window moves and resizes lag massively behind the pointer, and even operating the program is considerably less responsive than it's peers. (MadEdit, and wxMEdit)

I would guess something in the snap-on toolbands, and (personally) I'd rather just have static toolbars that this mess. Other features look really exciting, but MEM isn't usable to me just yet.

The example system is running Elementary OS Loki, but I've tried it on several Linux machines (mostly Elementary, GNOME 3 or xfce DEs but different versions and hardware) and the result is always the same.

I have not tried using a KDE (or other Qt based) DE system. (Kubuntu, for example)

**Comment by LiMinggang** [comment] 2017-10-06 16:08
Not sure if I could reproduce it. I don't have the OS you mentioned but will try to find a VM image on osboxes.org. The Linux dists I tried are Fedora Core, CentOS, Ubuntu/Debian, Mageia.

It might be a build issue----I mean some complex issue of the dependency of the version of the libs.

You don't need to try it with KDE because wxWidgets which was the base of the GUI of MadEdit relies on GNOME for Linux.

**Comment by LiMinggang** [comment] 2017-10-06 16:12
Which version of Loki are you using? X64 or X86? What is shown on the about dialog of MEM?

**Comment by bobsobol** [comment] 2017-10-07 00:56
Hmm. There's only one install medium for Loki, but I used the x64 Ubuntu deb package of MadEdit-Mod. Most of my hardware is 64-bit, so that's normally what I install, though I do have one of those silly devices with 32-bit EFI firmware that doesn't boot 64 bit OS. I don't think I've tried MEM on that.

I *can* definitely evidence that the same issue is present on x64 Ubuntu  GNOME 16.04.

![Ubuntu 16.04 GNOME](https://s1.postimg.org/1dv0nlydfj/MEM-_GNOME.png)

That machine is currently updated to 16.04.3 LTS, GTK 3.18.9, though I'll admit that it's a VM. However, the hosting hardware is completely different from the other system. Which, *suggests* it's not driver, or hardware related. elementaryOS is Ubuntu based though.

I have an OpenSUSE Tumbleweed VM running GNOME 3 too which would be a completely different distro, but I'm not too familiar with it, there isn't a package (though, it *can* read RPMs) and I struggled to locate the required dependencies to build the source. I have CentOS and FreeBSD servers, but they're headless, and I don't really want to put an X server on them. I could install a VM of either just to *try* but I suspect BSD would be even more an alien port than SUSE. XD

If you don't see it on Ubuntu, where I do, is it worth considering something more esoteric, like my default local, (UK English) or the fact that I tend to pick Greybird (by Daniel Foré aka DanRabbit) or derivative themes with deep window shadow? It's struck me before that the outer window is just about encompassing the shadow. ???

**Comment by LiMinggang** [comment] 2017-10-07 06:31
OK, will try me Ubuntu X64 first.

**Comment by LiMinggang** [comment] 2017-10-07 06:37
After investigating the code of wxMedit, MadEdit and MEM, I think it might be a bug from MadEdit. Will try the code of wxMedit to fix the issue.

**Comment by LiMinggang** [comment] 2017-10-09 02:11
It's tricky that I could not reproduce the issue with ubuntu 16.04.
![image](https://user-images.githubusercontent.com/4847132/31323425-2be316ec-acda-11e7-9973-f1a5b1fb1a40.png)

**Comment by LiMinggang** [comment] 2017-10-09 02:19
However, you can find the menu bar of MEM is on the system memu of Ubuntu. I'm not sure if this is why you see the double border. It was not a bug of MEM but some feature of Ubuntu if this is the root cause.

![image](https://user-images.githubusercontent.com/4847132/31323515-59eb4644-acdb-11e7-8c4e-576df0c1c073.png)

**Comment by LiMinggang** [comment] 2017-10-09 04:01
Confirmed with ElementaryOS 0.4.1

**Comment by bobsobol** [comment] 2017-10-09 08:23
Yes, the unified menu is a tweak implemented specifically, and only in the Unity DE. (now deprecated) From 18.x onward, Canonical have said they intend to produce a Unity *like* theme for GNOME 3, and GNOME Ubuntu 18.x will become the default distribution.

I've seen GNOME extensions which put menus in the system bar, but they don't do it in quite the same way. But that unified menu area isn't present in lubuntu, Kubuntu, Xubuntu, Ubuntu Studio etc. let alone derivatives like Mint, Zorin, elementaryOS etc.

This, from the [Ubuntu Wiki](https://wiki.ubuntu.com/MenuBar), may help test the issue, or work around the peculiarities of Unity:-

## Advertising the presence of the menu bar
In some cases, an application developer may want to use menus — or tweak the layout of the window — only if the unified menu bar is available. Examples include preferences windows, dialogs, and Chromium browser windows.

GTK application developers can use this code to detect whether a unified menu bar (or similar menu handler) is in use:
```
if (gtk_menu_proxy_get() != NULL) {
  ...
}
```
Qt application developers can use this equivalent code:
```
if (!QCoreApplication::testAttribute(Qt::AA_DontUseNativeMenuBar)) {
  ...
}
```

**Comment by LiMinggang** [comment] 2017-10-09 08:54
Hi, bobsobol, I tried a example of wxWidgets and found that the bug is from wxWidgets 3.1.0(wxMedit is using wxWidgets 3.0.x). I'm not sure when the developer can fix the bug or not.
Here is the example app of wxWidgets 3.1.0
![image](https://user-images.githubusercontent.com/4847132/31330714-12fe1d6a-ad12-11e7-818a-28dafd9a08c3.png)

I'll open an issue for them to track but the response would be extremely slow.

It's hard for me to debug and fix the issue because I've no idea about the issue. I'm not an expert of wxWidget itself.

Maybe I should use wxWidgets 3.0.3 to release 0.4.10 and later.

**Comment by LiMinggang** [comment] 2017-10-09 09:40
wxWidgets 3.0.3 has the same issue. I'm not sure if the root cause is GTK 3. wxMedit said it was "built with wxWidgets-3.0 GTK2". Will do more investigation.

**Comment by LiMinggang** [comment] 2017-10-09 12:10
Hi, bobsobol, I have a question about ElementaryOS Loki. Is it stable enough? The VM I downloaded from osboxes.net hanged several times and never came up again since then. I have to replace the image with the original one from osboxes.net again and again. I never met the issue with other VM images, eg, Ubuntu 32/64, Debian, Fedora, CentOS, Mageia 32/64, FreeBSD, etc.

I'll try Ubuntu to build wxWidgets with GTK 2 and give up the OS.

**Comment by LiMinggang** [comment] 2017-10-10 03:57
I can almost confirm this issue is from wxWidgets VS GTK3. The same sample app look OK if build with GTK2
![image](https://user-images.githubusercontent.com/4847132/31368748-37cfc03a-adb2-11e7-909b-676e7ae9dced.png)

**Comment by LiMinggang** [comment] 2017-10-10 04:23
MEM with GTK2 on ElementaryOS 0.4.1
![image](https://user-images.githubusercontent.com/4847132/31369269-d683b21a-adb5-11e7-95ba-b9cfe0acc6ae.png)

**Comment by LiMinggang** [comment] 2017-10-10 07:01
Do you wish to try the build on the OSes you mentioned and give me feedback? Eg, your ElementaryOS, Ubuntu GNOME and OpenSUSE? I can put the build in Preview directory.

I don't use Linux Desktop in my daily work.

**Comment by bobsobol** [comment] 2017-10-10 13:12
Sure!

The pixman errors indicate something is definitely going wrong with the wx library code though, and pixman is an area of GNOME 3 I've noticed often goes awry if you stray far from your distros repository, which suggests it's under very active development.

elementaryOS has proven fairly stable for me, in real hardware situations. I use it regularly on an Acer Revo, a Microsoft Sufrace Pro 3, an HP 250 notebook, and a self-build system, and live boot it on various devices. I will say that I've seen Gala (the compositor) be temperamental, either over remote desktop technologies and in VMs, depending how they implement hardware acceleration.

> It's a bit like Unity (or Compiz, or Fusion, or Emerald) in that respect, and is why Linux needs Wayland sooner rather than later. There should be only one. ;)

Unless you're directly developing against GTK+3, or a specifically GTK+3 engine (like Granite, in elementaryOS) I would probably stick to targeting GTK+2. GNOME3 is *so* nearly ready, but still under heavy active development, and flux.

**Comment by LiMinggang** [comment] 2017-10-11 02:04
https://sourceforge.net/projects/madedit-mod/files/Preview/

**Comment by bobsobol** [comment] 2017-10-16 15:12
Hi LiMinggang,
I *have* tried to do this, but am getting an incomplete, or corrupt .deb package each time.

The reason for the delay is that I've now tried it on three independent internet connections, to be sure there isn't a bad cache object between me and SourceForge. I'm now pretty certain there isn't. (unless there's a common element I'm not aware of ... "Great Firewall of China" [or, in my case, not China, but it still exists], or same AntiVirus engine "cleaning" the data between you and I, or such)

Can you recheck the upload, to be sure?

Sorry. :( I feel I'm being a pain.

**Comment by LiMinggang** [comment] 2017-10-17 00:15
Will do it with MD5 check to verify and make a tar ball. The local one is OK for my VM. It might be more censorship of GFW because of the incoming 19th Party of CCP.

**Comment by LiMinggang** [comment] 2017-10-17 02:50
This one should be OK with latest code

**Comment by bobsobol** [comment] 2017-10-17 13:09
Yes, that works. Looks good, and performs *much* better too.
![Seems Fixed](https://s1.postimg.org/5am2hfsa0v/Mad_Edit-_Mod_Seems_Fixed.png)
Illustrated are MadEdit-Mod GTK2, and wxMEdit handling a nice big 2½Gig BZipped drive image on a slow off-site Windows (smb/cifs) share back at the data-centre. Just to torture file read the performance of both. Neither are pretty trying to wiz the scroll bar, but neither are stalling the way the GTK3 build was, and they both perform comparably.

wxMEdit still looks a little more "native", as you can see. However, and while I use elementaryOS because aesthetics *do* matter to me, functionality is **far** more important with a tool like this.

Thanks *so* much for your efforts LiMinggang. I'll check in other environments and let you know if I find anything else interesting, but this looks really good so far. :)

**Comment by LiMinggang** [comment] 2017-10-17 13:36
OK. Will wait for you feedback before releasing 0.4.10.
Basically, the two should perform the same because both are based on MadEdit. I added more functions but they are not performance related. It might introduce more bugs sometimes.

**Comment by LiMinggang** [comment] 2017-10-19 03:54
Any update? Will release 0.4.10 if no update

**Comment by LiMinggang** [comment] 2017-10-23 02:12
Close the issue with 0.4.10

**Closed by LiMinggang** 2017-10-23 02:12 UTC
Labels: bug
